FROM agdrone/base_extractor_plot:1.0
LABEL maintainer="Someone <someone@example.com>"

COPY extractor_info.json extractor.py configuration.py /home/extractor/

# ADD ADDITIONAL INITIALIZATION STEPS HERE
